spring.application.name=service-registry
server.port=${SERVER_PORT}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.prefer-ip-address=true
spring.threads.virtual.enabled=true

management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.tracing.export.otlp.enabled=true
management.opentelemetry.tracing.export.otlp.timeout=30s

management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.read-timeout=30s

management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
management.logging.export.otlp.enabled=true
management.opentelemetry.logging.export.otlp.timeout=30s



management.endpoints.web.exposure.include=health,info,prometheus,otlp
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0