server:
  http_listen_port: ${TEMPO_HTTP_PORT}
distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: ${OTEL_HTTP_ENDPOINT}
        grpc:
          endpoint: ${OTEL_GRPC_ENDPOINT}

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: ${MEMBERLIST_BIND_PORT}

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

