spring.application.name=api-gateway
server.port=${SERVER_PORT}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.instance.prefer-ip-address=true
spring.threads.virtual.enabled=true
spring.main.web-application-type=servlet

resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=30s

jwt.secret-key=${JWT_SECRET_KEY}
internal.api-key=${INTERNAL_API_KEY}

management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_TRACES_ENDPOINT}
management.tracing.export.otlp.enabled=true
management.opentelemetry.tracing.export.otlp.timeout=30s

management.otlp.metrics.export.url=${OTEL_METRICS_ENDPOINT}
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.read-timeout=30s

management.opentelemetry.logging.export.otlp.endpoint=${OTEL_LOGS_ENDPOINT}
management.logging.export.otlp.enabled=true
management.opentelemetry.logging.export.otlp.timeout=30s



management.endpoints.web.exposure.include=health,info,prometheus,otlp
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0