spring.application.name=restaurant-service
server.port=${SERVER_PORT}
eureka.instance.prefer-ip-address=true

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

spring.datasource.url=${DB_URL}/food_restaurant_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.threads.virtual.enabled=true

internal.api-key=${INTERNAL_API_KEY}

spring.kafka.bootstrap-servers=${KAFKA_URL}
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.food.restaurant_service.dto.OrderEventDto
spring.kafka.consumer.properties.spring.json.use.type.headers=true
spring.kafka.consumer.properties.spring.json.type.mapping=com.food.order_service.dto.OrderEventDto:com.food.restaurant_service.dto.OrderEventDto
spring.kafka.template.observation-enabled=true
spring.kafka.listener.observation-enabled=true

management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_TRACES_ENDPOINT}
management.tracing.export.otlp.enabled=true
management.opentelemetry.tracing.export.otlp.timeout=30s

management.otlp.metrics.export.url=${OTEL_METRICS_ENDPOINT}
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.read-timeout=30s

management.opentelemetry.logging.export.otlp.endpoint=${OTEL_LOGS_ENDPOINT}
management.logging.export.otlp.enabled=true
management.opentelemetry.logging.export.otlp.timeout=30s


management.endpoints.web.exposure.include=health,info,prometheus,otlp
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0